import Navbar from '@/components/Navbar'
import './globals.css'

export const metadata = {
  title: 'Software Blogs',
  description: 'Generated by create next app',
}

const RootLayout = ({children}) => {
  return (
    <html lang="en">
      <body>
        <main className='max-w-screen-xl mx-auto'>
          <Navbar />
          {children}
        </main>
      </body>
    </html>
  );
};

export default RootLayout;