import Navbar from '@/components/Navbar'
import './globals.css'


export const metadata = {
  title: 'Software Blogs',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <main className='max-w-screen-lg mx-auto'>
          <Navbar />
          {children}
        </main>
      </body>
    </html>
  )
}
